// <auto-generated />
namespace goo.Driver.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ddase3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ddase3));
        
        string IMigrationMetadata.Id
        {
            get { return "201704212240043_ddase3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
